### ISSUE TITLE
Lost readme?

### ISSUE THREAD

**Issue by ziameanslight** [earthrise-media/food-system-digital-twin#1]
Looks like we lost the readme on a recent push (?).

**Comment by wrynearson** [comment]
cc @nerik

**Comment by nerik** [comment]
Hey @ziameanslight , sorry if I'm not getting that, is this about [this README](https://github.com/earthrise-media/food-system-digital-twin/blob/main/README.md) ?

**Comment by ziameanslight** [comment]
Aha, there it is. Thanks @nerik!
